classdef TestAWSAuthorization < matlab.unittest.TestCase
    % TESTCLIENT Unit Test for different Amazon Credentials Provider
    % Authorization.
    % To run test on GitLab: Ensure a `credentials.json` file is present in the MATLAB path.
    % To run test on Local Machine:
    %   1) AWS credentials should be stored in the `.aws` directory in your
    %   home folder. This can be generated by using AWS SAML.
    %   2) The credentials file should contain atleast your AWS Access Key ID and Secret Access Key.
    %
    % The test suite exercises different authentications of AWS Credentials Provider.

    % Copyright 2025 The MathWorks, Inc.


    properties
        logObj
        isOnGitlab
        credentialProvider
        credentials
    end

    methods (TestClassSetup)
        function checkGitlab(testCase)
            host=getenv('CI_RUNNER_DESCRIPTION');
            testCase.isOnGitlab = ~isempty(host);
        end
        function initAWSEnvVariables(testCase)

            if testCase.isOnGitlab
                testCase.credentials = loadConfigurationSettings('credentials.json');
            else
                userHome = getenv('HOME');
                if isempty(userHome) % If HOME is not set, try USERPROFILE (Windows)
                    userHome = getenv('USERPROFILE');
                end
                awsCredentialsPath = fullfile(userHome, '.aws', 'credentials');

                if isfile(awsCredentialsPath)
                    testCase.credentials = testCase.parseAWSCredentialsFile(awsCredentialsPath);
                else
                    error('AWS credentials file not found in the .aws directory.');
                end
            end
        end
    end

    methods (TestMethodSetup)
        function testSetup(testCase)
            testCase.logObj = Logger.getLogger();
            testCase.logObj.DisplayLogLevel = 'verbose';

        end

    end

    methods (TestMethodTeardown)
        function testTearDown(testCase) %#ok<MANU>

        end
    end

    methods (Test, TestTags = {'AuthUnit'})
        function testDefaultCredentialsProvider(testCase)

            [testCase.credentialProvider, awsRegion] = aws.auth.CredentialProvider.getDefaultCredentialProvider();

            testCase.verifyNotEmpty(awsRegion);
            testCase.verifyNotEmpty(testCase.credentialProvider);

        end

        function testProfileCredentialsProvider(testCase)

            testCase.credentialProvider = aws.auth.CredentialProvider.getProfileCredentialProvider( ...
                'default');

            testCase.assertTrue(isa(testCase.credentialProvider, ...
                'software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider'), ...
                'Wrong class');
            testCase.assertTrue(isjava(testCase.credentialProvider), ...
                'It should be a Java class');
            testCase.verifyNotEmpty(testCase.credentialProvider);

        end

        function testSessionCredentialProvider(testCase)

            testCase.credentialProvider = aws.auth.CredentialProvider.getSessionCredentialProvider( ...
                testCase.credentials.aws_access_key_id, testCase.credentials.aws_secret_access_key, ...
                testCase.credentials.aws_session_token);

            testCase.assertTrue(isa(testCase.credentialProvider.resolveCredentials(), ...
                'software.amazon.awssdk.auth.credentials.AwsSessionCredentials'), ...
                'Wrong class');
            testCase.assertTrue(isjava(testCase.credentialProvider), ...
                'It should be a Java class');
            testCase.verifyNotEmpty(testCase.credentialProvider);

        end

        function testBasicCredentialProvider(testCase)

            testCase.credentialProvider = aws.auth.CredentialProvider.getBasicCredentialProvider( ...
                testCase.credentials.aws_access_key_id, testCase.credentials.aws_secret_access_key);

            testCase.assertTrue(isa(testCase.credentialProvider.resolveCredentials(), ...
                'software.amazon.awssdk.auth.credentials.AwsBasicCredentials'), ...
                'Wrong class');
            testCase.assertTrue(isjava(testCase.credentialProvider), ...
                'It should be a Java class');
            testCase.verifyNotEmpty(testCase.credentialProvider);

        end

        function testJsonFileCredentialsProvider(testCase)
            % Create the object

            [testCase.credentialProvider, ~] =aws.auth.CredentialProvider.getJsonFileCredentialProvider('credentials.json');

            testCase.assertTrue(isa(testCase.credentialProvider.resolveCredentials(), ...
                'software.amazon.awssdk.auth.credentials.AwsSessionCredentials'), ...
                'Wrong class');
            testCase.assertTrue(isjava(testCase.credentialProvider), ...
                'It should be a Java class');
            testCase.verifyNotEmpty(testCase.credentialProvider);


        end


        function testInstanceProfileCredentialProvider(testCase)
            cp = aws.auth.CredentialProvider.getInstanceProfileCredentialProvider();
            testCase.assertTrue(isjava(cp));
            testCase.assertTrue(isa(cp, 'software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider'));
        end

        function testWebIdentityCredentialProvider(testCase)
            cp = aws.auth.CredentialProvider.getWebIdentityCredentialProvider();
            testCase.assertTrue(isjava(cp));
            testCase.assertTrue(isa(cp, 'software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider'));
        end

        function testProfileCredentialProviderDefault(testCase)
            cp = aws.auth.CredentialProvider.getProfileCredentialProvider();
            testCase.assertTrue(isjava(cp));
            testCase.assertTrue(isa(cp, 'software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider'));
        end

        function testJsonFileCredentialProviderBasic(testCase)
            jsonStruct = struct( ...
                'aws_access_key_id', testCase.credentials.aws_access_key_id, ...
                'aws_secret_access_key', testCase.credentials.aws_secret_access_key, ...
                'region', 'us-east-1');
            jsonText = jsonencode(jsonStruct);
            tempFile = [tempname, '.json'];
            fid = fopen(tempFile, 'w');
            fwrite(fid, jsonText);
            fclose(fid);

            [cp, region] = aws.auth.CredentialProvider.getJsonFileCredentialProvider(tempFile);
            testCase.assertTrue(isjava(cp));
            testCase.assertTrue(isa(cp.resolveCredentials(), 'software.amazon.awssdk.auth.credentials.AwsBasicCredentials'));
            testCase.verifyEqual(region, "us-east-1");

            delete(tempFile);
        end

    end


    methods (Access = private)
        function credentials = parseAWSCredentialsFile(~, filePath)
            % Simple parsing logic for AWS credentials file
            fileContent = fileread(filePath);
            credentials = struct();

            % Extract the access key ID
            accessKeyPattern = 'aws_access_key_id\s*=\s*(\S+)';
            accessKeyMatch = regexp(fileContent, accessKeyPattern, 'tokens', 'once');
            if ~isempty(accessKeyMatch)
                credentials.aws_access_key_id = accessKeyMatch{1};
            end

            % Extract the secret access key
            secretKeyPattern = 'aws_secret_access_key\s*=\s*(\S+)';
            secretKeyMatch = regexp(fileContent, secretKeyPattern, 'tokens', 'once');
            if ~isempty(secretKeyMatch)
                credentials.aws_secret_access_key = secretKeyMatch{1};
            end

            % Extract the session token, if available
            sessionTokenPattern = 'aws_session_token\s*=\s*(\S+)';
            sessionTokenMatch = regexp(fileContent, sessionTokenPattern, 'tokens', 'once');
            if ~isempty(sessionTokenMatch)
                credentials.aws_session_token = sessionTokenMatch{1};
            end

            % Verify that required fields are present
            if isempty(credentials.aws_access_key_id) || isempty(credentials.aws_secret_access_key)
                error('AWS credentials file is missing required fields.');
            end
        end

    end
end

