classdef TestPollyClient < matlab.unittest.TestCase
    % TestPollyClient Unit Test for the Amazon Polly Client

    % Copyright 2025 The MathWorks, Inc.

    properties
        logObj
        polly
        lexiconName = "matlabtestlexicon";
        isOnGitlab
        region = 'us-east-1'
    end

    methods(TestClassSetup)
        % Shared setup for the entire test class
        function testSetup(testCase)
            testCase.logObj = Logger.getLogger();
            testCase.logObj.DisplayLogLevel = 'verbose';
        end

        function checkGitlab(testCase)
            host = getenv('CI_RUNNER_DESCRIPTION');
            testCase.isOnGitlab = ~isempty(host);
        end

        function initializePollyClient(testCase)
            if testCase.isOnGitlab
                credentials = loadConfigurationSettings('credentials.json');
                credentialProvider = aws.auth.CredentialProvider.getSessionCredentialProvider( ...
                    credentials.aws_access_key_id, credentials.aws_secret_access_key, ...
                    credentials.aws_session_token);
                testCase.polly = aws.polly.Client('credentialsprovider', credentialProvider, ...
                    'region', testCase.region);
            else
                testCase.polly = aws.polly.Client('region', testCase.region);
            end
        end

        function putLexicon(testCase)

            lexiconContent = [
                '<?xml version="1.0" encoding="UTF-8"?>' ...
                '<lexicon version="1.0" ' ...
                'xmlns="http://www.w3.org/2005/01/pronunciation-lexicon" ' ...
                'alphabet="ipa" xml:lang="en-US">' ...
                '  <lexeme>' ...
                '    <grapheme>test1</grapheme>' ...
                '    <alias>test1</alias>' ...
                '  </lexeme>' ...
                '</lexicon>'
                ];

            % Put lexicon
            putResp = testCase.polly.putLexicon("name", testCase.lexiconName, "content", lexiconContent);
            testCase.verifyEqual(putResp.status, "Success");

        end
    end

    methods(TestClassTeardown)

        function deleteLexicon(testCase)

            % Delete lexicon
            delResp = testCase.polly.deleteLexicon("name", testCase.lexiconName);
            testCase.verifyEqual(delResp.status, "Success");

        end

    end

    methods(TestMethodSetup)
        % Setup for each test
    end

    methods(Test, TestTags = {'Unit'})
        function testConstructor(testCase)
            write(testCase.logObj, 'debug', 'Testing testConstructor');
            testCase.verifyClass(testCase.polly, 'aws.polly.Client');
        end

        function testDescribeVoices(testCase)
            allVoices = testCase.polly.describeVoices();
            englishVoices = testCase.polly.describeVoices(languageCode="en-US");

            testCase.verifyLessThanOrEqual(numel(englishVoices.voices), numel(allVoices.voices));

        end

        function testSynthesizeSpeechBasicMP3(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "This is MATLAB unit test for AWS Polly.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3");
            testCase.verifyNotEmpty(resp.audioStream);
            % Optionally write to file and check file existence
            fname = tempname + ".mp3";
            fid = fopen(fname, 'w');
            fwrite(fid, resp.audioStream, 'uint8');
            fclose(fid);
            testCase.verifyTrue(isfile(fname));
            delete(fname);
        end

        function testSynthesizeSpeechSSML(testCase)
            ssml = "<speak>Hello <break time='500ms'/> world!</speak>";
            resp = testCase.polly.synthesizeSpeech( ...
                "text", ssml, ...
                "voiceId", "Matthew", ...
                "outputFormat", "mp3", ...
                "textType", "ssml");
            testCase.verifyNotEmpty(resp.audioStream);
        end

        function testSynthesizeSpeechPCM(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Testing PCM output.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "pcm", ...
                "sampleRate", "16000");
            testCase.verifyNotEmpty(resp.audioStream);
            % Decode PCM and check basic audio properties
            samples = typecast(resp.audioStream, 'int16');
            testCase.verifyGreaterThan(numel(samples), 1000); % Should be some audio
        end

        function testSynthesizeSpeechSpeechMarks(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Hello world.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "json", ...
                "speechMarkTypesWithStrings", ["word","sentence"]);
            testCase.verifyNotEmpty(resp.audioStream);
            % Convert bytes to char (assume ASCII/UTF-8)
            jsonStr = native2unicode(resp.audioStream','UTF-8');
            testCase.verifyNotEmpty(jsonStr);
            testCase.verifyNotEmpty(contains(jsonStr, 'type'));
        end

        function testSynthesizeSpeechNeuralEngine(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Hello neural world.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "engine", "neural");
            testCase.verifyNotEmpty(resp.audioStream);
        end

        function testSynthesizeSpeechLexicon(testCase)

            % Get lexicon
            getResp = testCase.polly.getLexicon("name", testCase.lexiconName);
            testCase.verifyEqual(getResp.lexiconName, testCase.lexiconName);
            testCase.verifyNotEmpty(getResp.lexiconContent);
            testCase.verifySubstring(getResp.lexiconContent, "test1")

            % This assumes you have a lexicon uploaded named 'matlabtestlexicon'
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "The word is potato.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "lexiconNames", testCase.lexiconName);
            testCase.verifyNotEmpty(resp.audioStream);

        end

    end

    methods(Test, TestTags = {'Unit'})
        function testInvalidOutputFormat(testCase)
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "Hello world.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "wav"), ...
                'MATLAB:validators:mustBeMember');
        end

        function testSynthesizeSpeechLexiconInvalidName(testCase)
            % Lexicon name with hyphen (invalid)
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "The word is potato.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "lexiconNames", "example-lexicon"), ...
                'MATLAB:Java:GenericException');
        end

        function testSynthesizeSpeechLexiconTooLong(testCase)
            % Lexicon name too long (21 chars)
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "The word is potato.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "lexiconNames", "examplelexiconnametoolong"), ...
                'MATLAB:Java:GenericException');
        end

        function testSynthesizeSpeechLexiconInvalidChars(testCase)
            % Lexicon name with invalid chars
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "The word is potato.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "lexiconNames", "example_lexicon!"), ...
                'MATLAB:Java:GenericException');
        end

        function testSynthesizeSpeechLexiconNotFound(testCase)
            % Lexicon name that does not exist
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "The word is potato.", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "lexiconNames", "ThisLexiconDoesNotExist"), ...
                'MATLAB:Java:GenericException');
        end

        function testSynthesizeSpeechWithNeuralEngine(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Neural test", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "engine", "neural");
            testCase.verifyNotEmpty(resp.audioStream);
        end

        function testSynthesizeSpeechWithLanguageCode(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Bonjour", ...
                "voiceId", "Celine", ...
                "outputFormat", "mp3", ...
                "languageCode", "fr-FR");
            testCase.verifyNotEmpty(resp.audioStream);
        end

        function testSynthesizeSpeechInvalidLanguageCode(testCase)
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "Hello", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "languageCode", "xx-XX"), ...
                'MATLAB:error:invalidMessageType');

        end

        function testSynthesizeSpeechWithSampleRate(testCase)
            resp = testCase.polly.synthesizeSpeech( ...
                "text", "Sample rate test", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "sampleRate", "22050");
            testCase.verifyNotEmpty(resp.audioStream);
        end

        function testSynthesizeSpeechInvalidSampleRate(testCase)
            testCase.verifyError(@() testCase.polly.synthesizeSpeech( ...
                "text", "Bad rate", ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "sampleRate", "22k"), ...
                'AWS:Polly:InvalidSampleRate');
        end

        function testSynthesizeSpeechWithSSML(testCase)
            ssmlText = "<speak>Hello <break time='1s'/> world.</speak>";
            resp = testCase.polly.synthesizeSpeech( ...
                "text", ssmlText, ...
                "voiceId", "Joanna", ...
                "outputFormat", "mp3", ...
                "textType", "ssml");
            testCase.verifyNotEmpty(resp.audioStream);
        end

    end

end